services:
  postgres:
    container_name: waiting-list-postgres
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: waiting-list
    volumes:
      - waiting-list-postgres_data:/var/lib/postgresql/data

volumes:
  waiting-list-postgres_data:
